"""
domain/common/value_objects.py

Shared Value Objects used across all bounded contexts.
All are immutable Pydantic v2 BaseModels (frozen=True).
Invariants are enforced via @field_validator.
"""

from __future__ import annotations

from enum import Enum
from typing import Final

from pydantic import BaseModel, ConfigDict, field_validator

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

VALID_PROFICIENCY_LEVELS: Final[frozenset[str]] = frozenset(
    {"beginner", "intermediate", "advanced", "expert"}
)
VALID_PRIORITIES: Final[frozenset[str]] = frozenset({"low", "medium", "high"})


# ---------------------------------------------------------------------------
# Domain exceptions (live close to the VOs that raise them)
# ---------------------------------------------------------------------------


class InvalidMatchScoreError(Exception):
    """Raised when a MatchScore value is outside the 0-100 range."""


# ---------------------------------------------------------------------------
# Value Objects
# ---------------------------------------------------------------------------


class Skill(BaseModel):
    """
    Represents a concrete skill a candidate possesses or a job requires.

    Equality is purely value-based: two Skill instances with the same
    (name, category, proficiency_level) are identical.
    """

    model_config = ConfigDict(frozen=True)

    name: str
    category: str
    proficiency_level: str  # beginner | intermediate | advanced | expert

    @field_validator("name", "category")
    @classmethod
    def must_not_be_blank(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("must not be empty.")
        return v

    @field_validator("proficiency_level")
    @classmethod
    def validate_proficiency(cls, v: str) -> str:
        if v not in VALID_PROFICIENCY_LEVELS:
            raise ValueError(
                f"must be one of {sorted(VALID_PROFICIENCY_LEVELS)}, got {v!r}."
            )
        return v

    @property
    def normalised_name(self) -> str:
        return self.name.strip().lower()

    @property
    def normalised_category(self) -> str:
        return self.category.strip().lower()

    def matches(self, other: "Skill") -> bool:
        """True when name and category match case-insensitively."""
        return (
            self.normalised_name == other.normalised_name
            and self.normalised_category == other.normalised_category
        )


class MatchScore(BaseModel):
    """
    Represents the percentage match between a resume and a job posting.
    Value must be an integer in [0, 100].
    """

    model_config = ConfigDict(frozen=True)

    value: int

    def model_post_init(self, __context: object) -> None:
        """Validate range after Pydantic sets the field. Raises directly (not wrapped)."""
        if not (0 <= self.value <= 100):
            raise InvalidMatchScoreError(
                f"MatchScore.value must be between 0 and 100, got {self.value}."
            )

    @property
    def is_strong(self) -> bool:
        return self.value >= 75

    @property
    def is_acceptable(self) -> bool:
        return self.value >= 50

    @property
    def label(self) -> str:
        if self.value >= 75:
            return "strong"
        if self.value >= 50:
            return "acceptable"
        if self.value >= 25:
            return "weak"
        return "poor"


class Gap(BaseModel):
    """
    Represents a gap between what a job requires and what a resume provides.
    """

    model_config = ConfigDict(frozen=True)

    gap_type: str
    description: str

    @field_validator("gap_type", "description")
    @classmethod
    def must_not_be_blank(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("must not be empty.")
        return v


class ImprovementSuggestion(BaseModel):
    """
    An actionable recommendation generated by the matching engine to help
    a candidate improve their chances for a specific job.
    """

    model_config = ConfigDict(frozen=True)

    text: str
    priority: str    # low | medium | high
    category: str

    @field_validator("text", "category")
    @classmethod
    def must_not_be_blank(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("must not be empty.")
        return v

    @field_validator("priority")
    @classmethod
    def validate_priority(cls, v: str) -> str:
        if v not in VALID_PRIORITIES:
            raise ValueError(
                f"must be one of {sorted(VALID_PRIORITIES)}, got {v!r}."
            )
        return v
