# Generated by Django 6.0.4 on 2026-04-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumerecord',
            name='analysis_status',
            field=models.CharField(default='idle', max_length=20),
        ),
    ]
